---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
  labels:
    app: crossplane
    name: grafana-creds
type: Opaque
stringData:
  credentials: |
    {
      "url": "https://grafana.k8s.local,
      "auth": "eyJrIjoieUQ3ZHhuREdHR1daa2t1ODY0bk5ldExhUjl0NTQ2U1QiLCJuIjoidGVzdCIsImlkIjoxfQ=="
    }
