apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - whoami-ingress.yaml
  - whoami-deploy.yaml
  - whoami-svc.yaml

commonLabels:
  env: local

namespace: whoami
