apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - ingressroute.yaml
  - service.yaml

namespace: grafana
