apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      name: loki
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.4.2
          args:
            - -config.file=/etc/loki/loki.yml
          ports:
            - name: loki
              containerPort: 3100
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/loki.yml
              subPath: loki.yml
          resources:
            limits:
              memory: '1Gi'
              cpu: '1000m'
            requests:
              memory: 500M
              cpu: '500m'
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
