---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loki-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: loki
      path: "loki-storage"
