---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

generatorOptions:
  immutable: true

transformers:
  - |-
    apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: commonLabelsTransformer
    labels:
      app.kubernetes.io/name: whoami
      app.kubernetes.io/component: whoami
      app.kubernetes.io/part-of: whoami
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/stage: apps
      app.kubernetes.io/owner: hadenlabs

    fieldSpecs:
    - path: metadata/labels
      create: true
    - path: spec/template/metadata/labels
      create: true
      kind: Deployment
    - path: spec/selector/matchLabels
      create: true
      kind: Deployment
    - path: spec/template/metadata/labels
      create: true
      kind: DaemonSet
    - path: spec/selector/matchLabels
      create: true
      kind: DaemonSet
    - path: spec/template/metadata/labels
      create: true
      kind: Secrets
    - path: spec/selector/matchLabels
      create: true
      kind: Secrets
    - path: spec/secretTemplate/labels
      create: true
      kind: Certificate
    - path: spec/selector
      create: true
      kind: Service

resources:
  - configmap.yaml
  - secrets.yaml
  - grafana.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

images:
  - name: traefik/whoami
    newName: traefik/whoami
    newTag: latest
