apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: v0.13.9
    releaseName: metallb
    namespace: metallb-system
    includeCRDs: true
    valuesFile: ./values.yaml
commonAnnotations:
  meta.helm.sh/release-name: metallb
  meta.helm.sh/release-namespace: metallb-system
commonLabels:
  app.kubernetes.io/managed-by: Helm
