---
additionalArguments:
  - --api=true
  - --api.dashboard=true
  - --api.insecure=true

logs:
  general:
    level: INFO

ports:
  web:
    redirectTo: websecure

service:
  enabled: true
  single: true
  type: LoadBalancer
