---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasource.yml: |-
    apiVersion: 1

    datasources:
      - name: loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki:3100
        basicAuth: true
        basicAuthUser: ${LOKI_USER}
        jsonData:
          maxLines: 5000
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: ${LOKI_ORG_ID}
          basicAuthPassword: ${LOKI_PASSWORD}
        isDefault: true
        version: 1
        editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app: grafana
data:
  GF_SERVER_ROOT_URL: 'https://grafana.k8s.local'
  GF_SECURITY_ADMIN_USER: 'admin'
  GF_SECURITY_ADMIN_PASSWORD: 'password'
  GF_USERS_ALLOW_SIGN_UP: 'False'
  # loki
  LOKI_ORG_ID: '1'
  LOKI_USER: 'loki'
  LOKI_PASSWORD: 'v2ZL7Xun7UmA'
