apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
      containers:
        - name: grafana
          image: grafana/grafana:8.4.3
          ports:
            - name: grafana
              containerPort: 3000
          resources:
            limits:
              memory: '1Gi'
              cpu: '1000m'
            requests:
              memory: 500M
              cpu: '500m'
          envFrom:
            - configMapRef:
                name: grafana-config
            - secretRef:
                name: grafana-secret
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
              readOnly: false
      initContainers:
        - name: change-ownership-container
          image: busybox
          command: ['/bin/chown', '-R', '472:472', '/var/lib/grafana/']
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
