---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: grafana
      path: 'grafana-storage'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-datasources
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: grafana
      path: 'grafana-datasources'
