---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  labels:
    app: grafana
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: "YWRtaW4K"
  GF_SECURITY_ADMIN_PASSWORD: "cGFzc3dvcmQK"
  LOKI_USER: "bG9raQo="
  LOKI_PASSWORD: "djJaTDdYdW43VW1BCg=="
