---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: loki-storage
  labels:
    app: loki
    path: "loki-storage"
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/loki"
