---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-file.conf
    @INCLUDE output-loki.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*default*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Exclude_Path      *sender-service*
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Merge_Log_Key       data
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Keep_Log            On
        Annotations         On
  output-file.conf: |
    [OUTPUT]
        Name      file
        Path      /var/log
        File      output.txt
        Format    plain
        Match     *
  output-loki.conf: |
    [OUTPUT]
        name                    loki
        host                    ${FLUENT_LOKI_HOST}
        port                    ${FLUENT_LOKI_PORT}
        http_user               ${FLUENT_LOKI_USER}
        http_passwd             ${FLUENT_LOKI_PASS}
        tenant_id               ${FLUENT_LOKI_ORG_ID}
        match                   *
        labels                  job=fluentbit, pod=$kubernetes['pod_name'], app=$kubernetes['labels']['app'], namespace=$kubernetes['labels']['namespace'], environment=$kubernetes['labels']['environment']
        label_keys              $stream
        auto_kubernetes_labels  off
  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$
    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
    [PARSER]
        Name        appservices
        Format      regex
        Regex       ^\[(?<time>[\d\-TZ\:\,\+]*)\] \[(?<thread>.*)\] (?<level>[\w]*) (?<logger>[\w\d\.]*) - (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S
        Time_Keep   On
    [PARSER]
        Name        appservices-multiline-first
        Format      regex
        Regex       ^\[(?<time>[\d\-TZ\:\,\+]*)\] \[(?<thread>.*)\] (?<level>[\w]*) (?<logger>[\w\d\.]*) - (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S
        Time_Keep   On

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-environment
  labels:
    app: fluent-bit-environment
data:
  FLUENT_LOKI_HOST: 'loki.loki.svc.cluster.local'
  FLUENT_LOKI_ORG_ID: '1'
