---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/name: fluentbit
    k8s-app: fluent-bit-logging
    name: fluent-bit
    version: v1
    kubernetes.io/cluster-service: 'true'
spec:
  selector:
    matchLabels:
      name: fluent-bit
  template:
    metadata:
      labels:
        name: fluent-bit
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: 'true'
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          imagePullPolicy: Always
          image: fluent/fluent-bit:1.9.0
          ports:
            - containerPort: 2020
            - containerPort: 24224
          envFrom:
            - configMapRef:
                name: fluent-bit-environment
            - secretRef:
                name: fluent-bit-secret
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
